#!/usr/bin/env python

import argparse
import time, glob
from lora_gateway import LoRaGateway
import json


parser = argparse.ArgumentParser(description='Read from serial and echomessage')
parser.add_argument('-d', '--device', default=glob.glob("/dev/ttyACM*")[0], help='path to serial device')
parser.add_argument('-r', '--rate', default=115200, help='rate of serial communication',type=int)
parser.add_argument('-o', '--outfilename', default='output.csv', help='output file')
parser.add_argument('-p', '--pin', default=7, help='the digital pin we want to measure',type=int)
args = parser.parse_args()

port = args.device
rate = args.rate
PIN=args.pin

outfilename=str(args.outfilename)

DELAY_TIME = 1.0

# create a lora gateway object
LG = LoRaGateway(port,rate)

outfile = open(outfilename,"w")


try:

    # read the value of a digital pin
    LG.analog_read(PIN)
    
    # wait sufficient time to get response
    time.sleep(DELAY_TIME)
    
    # get the response (in 'dict' format)
    pkt = LG.pkt
    
    if not pkt is None:
        
        # print json to the command line
        print json.dumps(pkt)
       
        # write to a local output file
        #outfile.write("{recv_timestamp},{RSSI},{data}\n".format(**info))
        outfile.write(json.dumps(pkt))
        outfile.flush()
        
    else:
        print 'ERROR'
except Exception as exc:
    print "# WARNING caught exception: %s" % exc
finally:
    outfile.close()

