#!/usr/bin/env python

import argparse
import time, glob
from lora_gateway import LoRaGateway
import json

parser = argparse.ArgumentParser(description='Read from serial and echomessage')
parser.add_argument('-d', '--device', default=glob.glob("/dev/ttyACM*")[0], help='path to serial device')
parser.add_argument('-r', '--rate', default=115200, help='rate of serial communication',type=int)
parser.add_argument('-o', '--outfilename', default='output.json', help='output file')
parser.add_argument('-p', '--pin', default=10, help='the digital pin we want to measure',type=int)
args = parser.parse_args()

port = args.device
rate = args.rate
PIN=args.pin

outfilename=str(args.outfilename)

DELAY_TIME = 1.0

# create a lora gateway object
LG = LoRaGateway(port,rate)

outfile = open(outfilename,"a")


try:

    # read the value of a digital pin
    LG.digital_read(PIN)
    
    # get the response (in 'dict' format)
    pkt = LG.pkt
    
    if not pkt is None:
    
        json_out=json.dumps(pkt)
          
        # print json to the command line
        print json_out
        
        # write it to a file
        outfile.write(json_out)
        outfile.flush()
        
    else:
        print 'ERROR'
        
except Exception as exc:
    print "# WARNING caught exception: %s" % exc
    
finally:
    outfile.close()

