#!/usr/bin/env python
import sys, serial, time, json

BAUDRATE = 115200

if __name__ == "__main__":
    import glob
    import numpy as np
    ports = glob.glob("/dev/ttyUSB*")
    ser = serial.Serial(ports[0], baudrate=BAUDRATE)
    cmd = "LED?\n"
    ser.write(cmd.encode())
    resp = ser.readline().strip()
    while resp.startswith("#"):
        resp = ser.readline().strip()
    #format as JSON
    pkt = {'led':int(resp)}
    json.dump(pkt,sys.stdout)
    sys.stdout.write("\n")

