#!/usr/bin/env python
import sys, serial, time, json

BAUDRATE = 115200

if __name__ == "__main__":
    lines = []
    for line in sys.stdin:
        lines.append(line)
    lines = "\n".join(lines)
    #print lines
    data = json.loads(lines)
    #print data
    
    import glob
    ports = glob.glob("/dev/ttyUSB*")
    ports.sort()
    ser = serial.Serial(ports[-1], baudrate=BAUDRATE)
    cmd = ""
    if data.has_key("led"):
        state = data['led']
        if(state):
            cmd = "LED.ON\n"
        else:
            cmd = "LED.OFF\n"
    print cmd
    ser.write(cmd.encode())
